# Generated by Django 3.2.12 on 2023-10-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
                ('instock', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
